repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.100.0
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
      # remove terraform_checkov since we’ll use the official Checkov hook

  - repo: https://github.com/bridgecrewio/checkov
    rev: 3.2.471   # pin latest stable
    hooks:
      - id: checkov
        args: [--quiet, -d, .]   # optional: make it match your CLI usage
